website/views.py
from flask import Flask, Blueprint, render_template, request, url_for, redirect, session, flash, jsonify
from datetime import timedelta, datetime
from werkzeug.security import generate_password_hash, check_password_hash 
from .models import Users, UserPreferences, DDOE, SavedContent
from sqlalchemy.orm.attributes import flag_modified
import random
from flask_login import login_user, logout_user, login_required, UserMixin, current_user
from . import gpt, ddoecontent, caches
import json
import uuid


from . import app, db
views = Blueprint("views", __name__)

@app.before_request
def before_request_func():
    if not current_user:
        return redirect(url_for('views.login'))

@views.route('/login',  methods=['GET', 'POST'] )
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        permanentsesh = request.form.get('permanentsession') == 'true' #returns bool
        user = Users.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=permanentsesh)
                print('Logged in')
                flash('Log in sucessful', 'info ')
                return redirect(url_for('views.home')) 
            else:
                flash('Wrong Password')
        else:
            flash('Username does not exist')
                
                
    return render_template("login.html")

@views.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if not username or not password1:
            flash("Username or password cannot be empty!")
        elif len(password1) < 6 or len(username) < 6:
            flash("Username and password must contain at least 6 characters!")
        elif password1 != password2:
            flash("Passwords don't match!")
        else:
            username_exists = Users.query.filter_by(username=username).first()
            email_exists = Users.query.filter_by(email=email).first()
            if username_exists or email_exists:
                flash('Username or email already exists!')
            else:
                new_user = Users(username=username, email=email, password=generate_password_hash(password1))
                db.session.add(new_user)
                db.session.commit()
                login_user(new_user)
                flash('Sign up successful', 'info')
                return redirect(url_for('views.personalize'))

    return render_template('register.html')
   

@views.route('/personalize', methods = ['GET', 'POST'])
def personalize():
    if request.method == "POST":
        age = request.form.get('age')
        language = request.form.get('language')
        subjects = request.form.get('subjects')
        if subjects:
            subjects = json.loads(subjects)
        id = current_user.id
        usercreds = UserPreferences(user_id = id, age = age, language = language, subjects=subjects)
        db.session.add(usercreds)
        db.session.commit()
        return redirect(url_for("views.home")) #CHANGE THIS TO DDOE HOME

    return render_template('personalize.html')
    #if request.method == 'POST':
    

@views.route('/chatbot', methods=['GET', 'POST'])
@login_required
def chatbot():
    if current_user.is_authenticated:
        print('logged in')
    if request.method == "POST":
        user = UserPreferences.query.filter_by(user_id=current_user.id).first()
        age = user.age
        language = user.language
        prompt = request.form.get("prompt")
        reply = gpt.chat(prompt, age, language)
        return render_template("chatbot.html", reply = reply)
    else:
        return render_template("chatbot.html")
    

@views.route('/dangerous')
def dangerous():
    users = Users.query
    ddoe = DDOE.query
    pref = UserPreferences.query
    for i in users:
        db.session.delete(i)
    for i in ddoe:
        db.session.delete(i)
    for i in pref:
        db.session.delete(i)
    
    db.session.commit()
    return render_template('dangerous.html')

@views.route('/createtest', methods = ['GET', 'POST'])
@login_required
def create_test():
    if(request.method == "POST"):
        prompt = request.form.get("prompt")
        session['testprompt'] = prompt
        formats = request.form.get("format")
        return redirect(url_for("views.test", prompt=prompt, formats=formats))
    return render_template("create_test.html")

@login_required
@views.route("/test", methods=['GET', 'POST'])
def test():
    if request.method == "POST":
        questionanswers = {}
        questions_list = session.get('questions_list')

        for i in range(len(questions_list)):
            answer = request.form.get(f'answer{i}')
            questionanswers[questions_list[i]] = {
                'user_answer': answer,
            }

        session['questionanswers'] = questionanswers
        return redirect(url_for("views.checktest"))
    else: 
        userpref = UserPreferences.query.filter_by(user_id=current_user.id).first()
        age = userpref.age
        prompt = request.args.get('prompt')

        if prompt == 'random':
            prompt = gpt.ddoetopic(current_user.id)

        formats = request.args.get('formats')
        questionswc = gpt.create_test(prompt, age, formats)

        session['format'] = formats
        session['questionswc'] = questionswc
        session['questions_list'] = list(questionswc.keys())  # Store the keys for consistent indexing
        session['testtopic'] = prompt

        return render_template('test.html', questionswc=questionswc, formats=formats)

    


@login_required
@views.route("/checktest", methods=['GET', 'POST'])
def checktest():
    questionanswers = session.get('questionanswers') #question answers only having user_ans
    questionswc = session.get('questionswc')
    formats = session.get("format")
    questions_list = session.get('questions_list')
    
    #topic for S and W
    topic = session.get("testtopic").split(" ")[0].strip().lower() #CHECK ACCURACY OF THIS LINE IN THE FUTURE (WILL IGNORE FOR ABSTRACTION PURPOSES RIGHT NOW)
    
    questionanswers = gpt.checktest(questionanswers, formats, questions_list, questionswc)
    score = gpt.testsandw(questionanswers, current_user.id, topic)

    return render_template('check_test.html', score = score, questionanswers = questionanswers, questions_list = questions_list)

@login_required
@views.route("/checksandw", methods=['GET', 'POST'])
def checksandw():
    userpref = UserPreferences.query.filter_by(user_id=current_user.id).first()
    current_strengths = userpref.strengths or []
    new_strength = 'WHats UP'
    if new_strength not in current_strengths:
        userpref.strengths.append(new_strength)

                # Update the user preferences with the new strengths
        #userpref.strengths = current_strengths
        db.session.commit()
        print("stregnth added successfully")
    
    return render_template("checksandw.html", strengths=userpref.strengths, weaknesses=userpref.weaknesses)
@login_required
@views.route("/", methods=["GET", "POST"])
def home():
    today = datetime.now().date()
    ddoe = DDOE.query.filter_by(user_id=current_user.id).first()
    if request.args.get('topic'):
        ddoe.topic=request.args.get('topic')
        topic = ddoe.topic
        ddoe.description = gpt.ddoedescription(current_user.id, topic)
        ddoe.examples=gpt.ddoeexamples(current_user.id, topic)
        db.session.commit()

    if not ddoe:
        topic = gpt.ddoetopic(current_user.id)
        description = gpt.ddoedescription(current_user.id, topic)
        examples = gpt.ddoeexamples(current_user.id, topic)
        word = gpt.ddoeword(current_user.id)
        ddoe = DDOE(
            user_id=current_user.id, 
            topic=topic, 
            description=description, 
            examples=examples, 
            last_updated=today, 
            previous_topics=[topic], 
            word=word, 
            previous_words=[word],
            current_streak=1
        )
        db.session.add(ddoe)
        db.session.commit()
        print(f"New DDOE created: {ddoe}")

    if ddoe.last_updated != today or request.method == "POST":
        yesterday = today - timedelta(days=1)
        
        if ddoe.last_updated == yesterday:
            ddoe.current_streak += 1
        else:
            ddoe.current_streak = 1
        
        num = random.randint(0, 3)
    
        ddoe.topic = gpt.ddoetopic(current_user.id)
        ddoe.description = gpt.ddoedescription(current_user.id, ddoe.topic)
        ddoe.examples = gpt.ddoeexamples(current_user.id, ddoe.topic)
        ddoe.word = gpt.ddoeword(current_user.id)
        ddoe.definition = gpt.ddoedefinition(ddoe.word)
        ddoe.last_updated = today
        
        if not ddoe.previous_topics:
            ddoe.previous_topics = []
        if not ddoe.previous_words:
            ddoe.previous_words = []
        
        ddoe.previous_topics.append(ddoe.topic)
        ddoe.previous_words.append(ddoe.word)

        db.session.commit()
        print(f"{ddoe.topic}, {ddoe.previous_topics}, {ddoe.word}, {ddoe.last_updated}, {today}, {request.method}")

    session['ddoetopic'] = ddoe.topic
    session['description'] = ddoe.description
    session['examples'] = ddoe.examples
    
    return render_template('home.html', topic=ddoe.topic, description=ddoe.description, examples=ddoe.examples, word=ddoe.word, definition = ddoe.definition)
    

@login_required
@views.route('/previoustopics')
def previous_topics():
    ddoe = DDOE.query.filter_by(user_id=current_user.id).first()
    previous_topics = ddoe.previous_topics
    return render_template('prevtopic.html', previous_topics = previous_topics)

website/templates/account.html
{% extends 'index.html' %}
{% block content %}
    <h1>Welcome {{user.username}}!</h1>
    <p>Your current streak is {{current_streak}}</p>
    
{% endblock %}

website/templates/articles.html
{% extends 'index.html' %} 

{% block headers %}
    <title>Jearn - Articles</title>
    <style>
        .modal-dialog.modal-dialog-scrollable {
            max-width: 90vw; /* 90% of the viewport width */
            height: 100vh; /* 90% of the viewport height */
            margin: 5vh auto; /* center the modal vertically */
        }
        .embed-responsive {
            height: 100%;
            width: 100%;
        }

        .embed-responsive iframe {
            height: 100%;
            width: 100%;
            border: none;
        }
    </style>
{% endblock %}

{% block content %}



    <h1>Articles - {{ topic }}</h1>
    <hr>
    <div class="container mt-5" id="articles-container">
        <div class="row" id="articles-row">
            {% for article in articles %}
                <div class="col-md-12 d-flex justify-content-center my-5 article-card">
                    <div class="card" style="width: 60vw;">
                        <div class="card-body">
                            <h5 class="card-title">{{ article.title }}</h5>
                            <p class="card-text">{{ article.content.introduction | truncate(100) }}...</p>
                            <a href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#postModal{{ loop.index }}">View Post</a>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="postModal{{ loop.index }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">{{ article.title }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                {% if article.media %}
                                    <div class="media">
                                        <img src="{{ article.media[0].src }}" class="mr-3" alt="{{ article.media[0].alt }}">
                                    </div>
                                {% endif %}
                                {% if article['url'] %}
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" src="{{ article['url'] }}" allowfullscreen></iframe>
                                </div>
                                {% else %}
                                    {% for section in article.content.sections %}
                                        <h5>{{ section.section_title }}</h5>
                                        <p>{{ section.section_content }}</p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <hr>
    <div class="row">
        <section id="form-section" class="section form-section d-flex align-items-center" style="height: 30vh;">
            <div class="container-lg d-flex flex-column align-items-center">
                <div class="d-flex justify-content-center gap-3">
                    <form method="POST" id="continueForm" action="{{ url_for('views.articles') }}">
                        <input type="hidden" name="topic" value="{{ topic }}">
                        <button type="submit">Continue learning about {{ topic }}</button>
                    </form>

                    <form method="POST" id="recommendForm" action="{{ url_for('views.articles') }}">
                        <input type="hidden" name="topic" value="recommend">
                        <button type="submit">Recommend a topic!</button>
                    </form>
                    <br>

                    <form method="POST" id="topicForm" action="{{ url_for('views.articles') }}">
                        <label for="topic">Enter custom topic</label>
                        <input id="topic" name="topic" type="text" placeholder="Enter a topic">
                        <button type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </section>
    </div>


<script>
   

</script>

{% endblock %}

website/templates/chatbot.html
{% extends "index.html" %}
<head>
    <title>Jearn - ChatBot</title>
</head>
{% block content %}
<body>
    <form method = "POST">
        <label>ChatGPT Preference</label>
        <input name="age" type="number" placeholder="what grade are you in?">
        <input name="prompt" type="text" placeholder="What are you interested in?">
        <input name="language" type="text" placeholder="languyage">
        <input type="submit">	

    </form>
    
    <h1> ChatGPT Reply</h1>
    <p> {{reply}}</p>

</body>
</html>
{% endblock %}

website/templates/check_test.html
{% extends 'index.html' %}

{% block headers %}
    <title>Check your test answers!</title>
{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Test Results</h1>
        <p>Your overall score is {{score * 100}}%</p>
        <hr>
        <div class="row">
            {% set i = 0 %}
            {% for question in questionanswers %}
                <div class="col-md-6 mb-4">
                    <div class="card">
                        <div class="card-header">
                            Question {{loop.index}}
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ question }}</h5>
                            {% if questionanswers[question]['is_correct'] == 1 %}
                                <div class="alert alert-success" role="alert">
                                    Your answer is correct!
                                </div>
                                <p class="card-text">Correct Answer: <strong>{{questionanswers[question]['correct_answer']}}</strong></p>
                            {% elif questionanswers[question]['is_correct'] == 0 %}
                                <div class="alert alert-danger" role="alert">
                                    Sorry, your answer is wrong.
                                </div>
                                <p class="card-text"> The correct answer was: <strong> {{questionanswers[question]['correct_answer']}}</strong></p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="text-center">
            <a href="{{ url_for('views.create_test')}}">Create another test!</a>     
        </div>
    </form>
    </div>

  
<!-- Sidebar is handled by the parent template -->

{% endblock %}

website/templates/create_test.html
{% extends "index.html" %}
{% block headers %}
<head>
    <title>Jearn - Custom Test</title>
    <style>
        /* Optional: Add any custom styles here if needed */
    </style>
</head>
{% endblock %}
{% block content %}
<h1 class="text-center">AI-generated Test</h1>
<hr>
<div class="container-fluid formcontainer d-flex justify-content-center align-items-center">
    <form action="/createtest" method="POST">
        <div class="mb-3">
            <label for="topic" class="form-label">Prompt for test</label>
            <input id="topic" class="form-control" name="prompt" type="text" placeholder="Enter topic">
        </div>
        <hr>
        <div class="mb-3">
            <label for="format" class="form-label">Choose your format</label> <br>
            <input type="hidden" id="format-input" name="format" value="">
            <button type="button" class="test-button button btn btn-outline-primary" id="format-written" onclick="setAnswer('written', 'format-written')">
                Written
            </button>
            <button type="button" class="test-button button btn btn-outline-primary" id="format-mcq" onclick="setAnswer('mcq', 'format-mcq')">
                Multiple Choice
            </button>
        </div>
        
        <button type="submit" class="btn btn-primary ">Submit</button>
        <a href="{{ url_for('views.test', prompt='random', formats='written') }}">Give me a random topic!</a>
    </form>
    
</div>
<script>
    function setAnswer(format, buttonId) {
        // Set the value of the hidden input to the selected format
        document.getElementById('format-input').value = format;

        // Get all buttons for the format selection
        const buttons = document.querySelectorAll('.test-button');

        // Remove the 'btn-primary' class from all buttons
        buttons.forEach(button => {
            button.classList.remove('btn-primary');
            button.classList.add('btn-outline-primary'); // Ensure all buttons have the outline style
        });

        // Add the 'btn-primary' class to the clicked button
        const selectedButton = document.getElementById(buttonId);
        selectedButton.classList.remove('btn-outline-primary');
        selectedButton.classList.add('btn-primary');
    }
</script>
{% endblock %}

website/templates/dangerous.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dangerous</title>
</head>
<body>
    What are you doing here?
</body>
</html>

website/templates/home.html
{% extends "index.html" %}

{% block content %}
<head>
    <title>Jearn - Home</title>
    <style>
        .hidden {
            display: none;
        }

        #revealButton {
            margin: 10px;
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
        }
        .section:not(.more-section){
            min-height: calc(100vh - 56px);
        }
        .more-section{
            height: 20vh;
            background-color: #EAECF6
        }
    
        .title-section {
        background-color: #c1ccff; /* Blue */
        text-align: center;
        }
        .word-section{
            background-color: #FDF4CD;
            text-align: center;
        }
        .content-section{
            background-color: #FFFF;
        }
        .topic-section {
        background-color: #F5C2C0; /* Blue */
        text-align: center;
        }

    </style>
</head>
<body>
    <section class="section title-section d-flex align-items-center">
        <div class="container-lg">
          <h1>Daily Dose of Education</h1>
          <p>Where your personalized learning journey begins.</p>
          <br>
          <a href = "#topic-section" class="btn btn-outline-primary" >Reveal Topic</a>
        </div>
    </section>
    <section id = "topic-section" class="section topic-section d-flex align-items-center">
        <div class="container-lg">
            <p>Today's topic is.</p>
          <h1>{{topic}}</h1>
          <br>
          <a href = "#content-section" class="btn btn-outline-primary" >Learn More</a>
          <br>
          <a class="sidebar-button" style="color: black;" href="{{ url_for('views.previous_topics') }}">View Past Topics</a>

        </div>
    </section>
    <section id = "content-section" class="section content-section d-flex align-items-center">
        <div class="container-lg">
            <h2 class="text-center">{{topic}}</h2>
            <hr>
            <p>{{description}}</p>
            
            <strong>Examples include: </strong>
            <hr>
            <p>{{examples}}</p>
            <a href = "#word-section" class="btn btn-outline-primary" >Reveal Word of the Day</a>

        </div>
    </section>
    <section id = "word-section" class="section word-section d-flex align-items-center">
        <div class="container-lg">
            <h1>{{word}}</h1>
            <p>{{definition}}</p>
            <a href = "#more-section" class="btn btn-outline-primary" >More</a>

        </div>
    </section>
    <section id="more-section" class="section more-section d-flex align-items-center" style="height: 20vh;">
        <div class="container-lg d-flex flex-column align-items-center">
          <div class="d-flex justify-content-center gap-3">
            <a href="{{ url_for('views.test', prompt=topic, formats='written') }}" style="height: 38px">Take a test about {{ topic }}</a>
            <form method="POST" id="newTopicForm" action="{{ url_for('views.home') }}" class="d-inline-block">
              <input type="hidden" name="topic" value="newtopic">
              <button type="submit" class="btn btn-secondary">Give Me a New Topic</button>
            </form>
          </div>
        </div>
    </section>




</body>
</html>
{% endblock %}

website/templates/login.html
{% extends 'index.html' %}
{% block headers %}
<style>
    .formcontainer{
        height: calc(100vh - 140px);
    }
</style>
<title>Jearn - Login</title>
{% endblock %}

{% block content %}
<h1 class="text-center">Login</h1>
<hr>

<div class="container-fluid formcontainer d-flex justify-content-center align-items-center">
    <form action="/login" method="POST" class="w-50">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input id="username" class="form-control" name="username" type="text" placeholder="Enter your username">
        </div>
        <hr>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input id="password" name="password" class="form-control" type="password" placeholder="Enter your password">
        </div>
        <div class="mb-3 form-check">
            <input id="permanentsession" name="permanentsession" type="checkbox" class="form-check-input" value="true">
            <label for="permanentsession" class="form-check-label">Stay logged in?</label>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <a id="link-register" href="/register" class="text-center">Don't have an account?</a>
    </form>
    
</div>
{% endblock %}

website/templates/personalize.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personalize</title>
</head>
<body>
    <p>This is all confidential information. This will not get shared with anyone else.</p>
    <form id="myForm" action="/personalize" method="POST">
        <br>
        <div>
            <label>What is your age?</label><br>
            <input name="age" type="number" min="1" oninput="validateInput(this)" placeholder="How old are you!">
        </div>
        <br>
        <div>
            <label>What language are you most familiar with?</label><br>
            <input name="language" type="text" placeholder="Input your language">
        </div>
        <div>
            <input type="text" id="textInput" placeholder="Interested subjects">
            <button type="button" onclick="addText()">Add</button>
            
            <ul id="textList"></ul>
        </div>
        <br>
        <input type="hidden" name="subjects" id="subjectsInput">
        <button type="submit">Submit</button>
    </form>

    <script>
        function addText() {
            const textInput = document.getElementById('textInput');
            const textValue = textInput.value.trim();

            if (textValue) {
                const textList = document.getElementById('textList');

                const listItem = document.createElement('li');
                listItem.className = 'entry';

                const textNode = document.createElement('input');
                textNode.type = 'text';
                textNode.value = textValue;
                textNode.readOnly = true;

                const removeButton = document.createElement('button');
                removeButton.textContent = 'Remove';
                removeButton.onclick = () => textList.removeChild(listItem);

                listItem.appendChild(textNode);
                listItem.appendChild(removeButton);

                textList.appendChild(listItem);

                textInput.value = ''; // Clear the input field
                updateHiddenInput();
            }
        }

        function updateHiddenInput() {
            const subjects = [];
            document.querySelectorAll('#textList .entry input[type="text"]').forEach(input => {
                subjects.push(input.value);
            });
            document.getElementById('subjectsInput').value = JSON.stringify(subjects);
        }

        document.getElementById('myForm').addEventListener('submit', function(event) {
            updateHiddenInput();
        });
    </script>
</body>
</html>

website/templates/prevtopic.html
{% extends 'index.html' %}
{% block content %}
{% for topic in previous_topics %}
    <form>
        <a href="{{ url_for('views.home', topic = topic) }}">{{topic}}</a>
    </form>

{% endfor %}
{% endblock %}

website/templates/register.html
{% extends 'index.html' %}
{% block headers %}
<style>
    .formcontainer{
        min-height: calc(100vh - 140px);
    }
</style>
<title>Jearn - Register</title>
{% endblock %}

{% block content %}
<h1 class="text-center">Register</h1>
<hr>

<div class="container-fluid formcontainer d-flex justify-content-center align-items-center">
    <form action="/register" method="POST" class="w-50">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input id="username" class="form-control" name="username" type="text" placeholder="Enter your username">
        </div>
        <hr>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input id="email" name="email" class="form-control" type="email" placeholder="Enter your email">
        </div>
        <hr>
        <div class="mb-3">
            <label for="password1" class="form-label">Password</label><br>
            <input id="password1" class = 'form-control' name="password1" type="password" placeholder="Enter your password">
        </div>
        <hr>
        <div class="mb-3">
            <label for="password2" class="form-label">Confirm password</label><br>
            <input id="password2" class = 'form-control' name="password2" type="password" placeholder="Confirm your password">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
        <a id="link-login" href="/login" class="text-center">Already have an account?</a>
    </form>
    
</div>
{% endblock %}